"""brd_v8_schema_upgrade

Revision ID: 846b8224c412
Revises: 00f002f03b4c
Create Date: 2026-04-13 10:06:37.370485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '846b8224c412'
down_revision: Union[str, None] = '00f002f03b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new enum values to requeststatus
    op.execute("ALTER TYPE requeststatus ADD VALUE IF NOT EXISTS 'ai_processing'")
    op.execute("ALTER TYPE requeststatus ADD VALUE IF NOT EXISTS 'pending_assignment'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etariff_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('query_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('request_files', 'ai_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('requests', sa.Column('ai_processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requests', sa.Column('ai_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requests', sa.Column('ai_draft_s3_key', sa.String(length=500), nullable=True))
    op.add_column('requests', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('requests', sa.Column('internal_note', sa.Text(), nullable=True))
    op.add_column('requests', sa.Column('has_downloaded', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('requests', sa.Column('has_rated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('requests', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('rating_comment', sa.Text(), nullable=True))
    op.add_column('requests', sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('requests', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'delivered', 'cancelled', name='requeststatus'),
               nullable=False)
    op.create_foreign_key(None, 'requests', 'users', ['approved_by'], ['id'])
    op.alter_column('tenant_email_configs', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tenant_email_configs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('tenants', sa.Column('favicon_s3_key', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('footer_text', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('tagline', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('fallback_email_domain', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('owner_name', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('owner_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('owner_phone', sa.String(length=20), nullable=True))
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tenants', 'etariff_daily_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('result_email', sa.String(length=255), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'result_email')
    op.alter_column('tenants', 'etariff_daily_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tenants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('tenants', 'owner_phone')
    op.drop_column('tenants', 'owner_email')
    op.drop_column('tenants', 'owner_name')
    op.drop_column('tenants', 'fallback_email_domain')
    op.drop_column('tenants', 'tagline')
    op.drop_column('tenants', 'footer_text')
    op.drop_column('tenants', 'favicon_s3_key')
    op.alter_column('tenant_email_configs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tenant_email_configs', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.alter_column('requests', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'delivered', 'cancelled', name='requeststatus'),
               nullable=True)
    op.drop_column('requests', 'rated_at')
    op.drop_column('requests', 'rating_comment')
    op.drop_column('requests', 'rating')
    op.drop_column('requests', 'has_rated')
    op.drop_column('requests', 'has_downloaded')
    op.drop_column('requests', 'internal_note')
    op.drop_column('requests', 'approved_at')
    op.drop_column('requests', 'approved_by')
    op.drop_column('requests', 'ai_draft_s3_key')
    op.drop_column('requests', 'ai_completed_at')
    op.drop_column('requests', 'ai_processing_started_at')
    op.alter_column('request_files', 'ai_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_table('etariff_usage_logs')
    # ### end Alembic commands ###
